# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-22 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_path',
            field=models.CharField(default='', max_length=50),
        ),
    ]
