# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sroom1',
            old_name='sid1',
            new_name='sid',
        ),
        migrations.RemoveField(
            model_name='sroom1',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='sroom1',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='sroom1',
            name='sid2',
        ),
    ]
