# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0002_auto_20180307_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sroom2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.DateTimeField()),
                ('sid', models.TextField()),
            ],
        ),
    ]
